/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import javax.swing.JOptionPane;
import Conexion.Conexion;
import UpperEssential.UpperEssentialLookAndFeel;
import java.awt.event.ActionListener;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Admin
 */
public class ModificarArreglo extends javax.swing.JFrame {

    CallableStatement cst;
    Connection cn;
    Statement stm;
    ResultSet rs;
    
    public ModificarArreglo() {
        initComponents();
        CargarCategoria();
        this.setLocationRelativeTo(null);

        txtNombre.setEnabled(false);
        txtDesc.setEnabled(false);
        txtCate.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtStock .setEnabled(false);
        btnModificar.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        btnModificar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnModificar1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnVendedor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 915));
        setMinimumSize(new java.awt.Dimension(1600, 915));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 915));
        getContentPane().setLayout(null);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(730, 520, 320, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("CODIGO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 330, 240, 50);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel2.setText("NOMBRE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 390, 240, 50);
        getContentPane().add(txtCate);
        txtCate.setBounds(730, 640, 320, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel3.setText("DESCRIPCION:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(550, 450, 270, 50);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel4.setText("PRECIO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 510, 240, 50);

        jLabel5.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel5.setText("STOCK:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(550, 570, 230, 50);
        getContentPane().add(txtStock);
        txtStock.setBounds(730, 580, 320, 40);

        jLabel6.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel6.setText("CATEGORIA:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(550, 630, 260, 50);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(730, 340, 240, 40);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(730, 400, 320, 40);
        getContentPane().add(txtDesc);
        txtDesc.setBounds(730, 460, 320, 40);

        btnModificar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2_icon-icons.com_61199.png"))); // NOI18N
        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(600, 710, 320, 70);

        jLabel9.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel9.setText("BUSCAR NOMBRE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 270, 280, 50);

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblLista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 330, 480, 460);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1430, 790, 110, 60);

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8761.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(1160, 300, 310, 70);

        btnModificar1.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnModificar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2_icon-icons.com_61199.png"))); // NOI18N
        btnModificar1.setText("Modificar");
        btnModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar1);
        btnModificar1.setBounds(1160, 390, 310, 70);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(1160, 480, 310, 70);

        btnLista.setBackground(new java.awt.Color(255, 255, 255));
        btnLista.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/list-on-a-notebook-stroke-symbol_icon-icons.com_57808.png"))); // NOI18N
        btnLista.setText("Lista     ");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLista);
        btnLista.setBounds(1160, 570, 320, 70);

        btnVendedor.setBackground(new java.awt.Color(255, 255, 255));
        btnVendedor.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vendedor.png"))); // NOI18N
        btnVendedor.setText("Trabajadores");
        btnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(btnVendedor);
        btnVendedor.setBounds(1160, 660, 320, 70);

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel7.setText("Bienvenido");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1190, 220, 280, 70);

        fondo1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        fondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(fondo1);
        fondo1.setBounds(1130, 210, 380, 560);

        jLabel8.setFont(new java.awt.Font("Segoe Script", 3, 160)); // NOI18N
        jLabel8.setText("Rosa Belén");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(260, 10, 960, 180);

        cbxCategoria.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCategoria);
        cbxCategoria.setBounds(190, 210, 320, 50);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel11.setText("CATEGORIA:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 220, 220, 32);

        btnOK.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        getContentPane().add(btnOK);
        btnOK.setBounds(990, 340, 59, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
 
        String codigo, nombre, descrip, cate ;
        int stock;
        double precio;
        
        codigo = this.txtCodigo.getText();
        nombre = this.txtNombre.getText();
        descrip = this.txtDesc.getText();
        cate = this.txtCate.getText();
        precio = Double.parseDouble(this.txtPrecio.getText());
        stock = Integer.parseInt(this.txtStock.getText());  
        
        modificarArreglo(codigo,nombre,descrip,cate,precio,stock);
        
        EntradaAdmin entrar = new EntradaAdmin();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        RegistrarArreglo entrar = new RegistrarArreglo();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar1ActionPerformed
        ModificarArreglo entrar = new ModificarArreglo();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        EliminarArreglo entrar = new EliminarArreglo();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        EntradaAdmin entrar = new EntradaAdmin();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendedorActionPerformed
        VerTrabajadores entrar = new VerTrabajadores();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVendedorActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        listarCategoria();
        Llenar();
    }//GEN-LAST:event_cbxCategoriaActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        txtCodigo.setEnabled(false);
        txtNombre.setEnabled(true);
        txtDesc.setEnabled(true);
        txtCate.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtStock .setEnabled(true);
        btnModificar.setVisible(true);
        
        Connection cn=null;
        Vector registros=null;
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn=DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=Floreria;"
               +"user=sa;password=123456");
            Statement stm=cn.createStatement();
            String query2="Select distinct * from Arreglo A join categoriaArreglo C"
                    + " on(A.categ = C.cod_cat)where A.cod = '" + txtCodigo.getText() + "'";
            ResultSet rs=stm.executeQuery(query2);
            registros=new Vector();
            while(rs.next()){
                txtNombre.setText(rs.getString("nombre"));
                txtDesc.setText(rs.getString("descrip"));
                txtPrecio.setText(rs.getString(String.valueOf("precio")));
                txtStock.setText(rs.getString(String.valueOf("stock")));
                txtCate.setText(rs.getString("nombre_cat"));
                
            }
        }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane, e.getMessage());    
        }catch(ClassNotFoundException e){}
    }//GEN-LAST:event_btnOKActionPerformed

    public void CargarCategoria(){
        Connection cn=null;
        Vector registros=null;
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn=DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=Floreria;"
               +"user=sa;password=123456");
            Statement stm=cn.createStatement();
            String query2="Select distinct * from categoriaArreglo";
            ResultSet rs=stm.executeQuery(query2);
            registros=new Vector();
            while(rs.next()){
                cbxCategoria.addItem(rs.getString("nombre_cat"));                
            }
        }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane, e.getMessage());    
        }catch(ClassNotFoundException e){}

    }
    
    private Vector listarCategoria() {
         Connection con=null;
         Statement stm=null;
         Vector reg=null;
         try{
         con = Conexion.getConexion();
         stm=con.createStatement();
         ResultSet rs = stm.executeQuery("SELECT * FROM Arreglo A JOIN categoriaArreglo C"
                 + " ON A.categ = C.cod_cat ");
         reg = new Vector();

             while(rs.next()){
             Vector item = new Vector();
             item.add(rs.getString("cod"));
             item.add(rs.getString("nombre"));
             //item.add(rs.getInt("stock"));
             //item.add(rs.getString("nombre_cat"));
             reg.add(item);
             }
         }
         catch(Exception e){
         System.out.print(e);
         }
         return reg;
    }
        
    private void close(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea Volver al Inicio?",
                "Cerrar Ventana", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
          Login c = new Login();
          c.setVisible(true);
          dispose();
        }          
    } 

    private Vector listar() {
         Connection con=null;
         Statement stm=null;
         Vector reg=null;
         try{
         con = Conexion.getConexion();
         stm=con.createStatement();
         ResultSet rs = stm.executeQuery("SELECT * FROM Arreglo A JOIN categoriaArreglo C"
                 + " ON A.categ = C.cod_cat and nombre_cat='"+cbxCategoria.getSelectedItem()+"' ");
         reg = new Vector();

             while(rs.next()){
             Vector item = new Vector();
             item.add(rs.getString("cod"));
             item.add(rs.getString("nombre"));
             reg.add(item);
             }
         }
         catch(Exception e){
         System.out.print(e);
         }
         return reg;
    }
        
    private void Llenar() {
        Vector colu = new Vector();
        colu.addElement("Codigo");
        colu.addElement("Nombre");       
        Vector reg = new Vector();
        reg = listar();
        DefaultTableModel dtm = new DefaultTableModel(reg, colu);
        this.tblLista.setModel(dtm);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel("C:\\Users\\Janet\\Desktop\\26-11-17\\Lib UpperEssential\\Chocolate.theme"));
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new ModificarArreglo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnVendedor;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtCate;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

    private void modificarArreglo(String codigo, String nombre, String descrip, String cate, double precio, int stock) {
            try {
            cst = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"
            + "database=Floreria;user=sa;password=123456;").prepareCall("{call sp_Modificar(?,?,?,?,?,?)}");            
            cst.setString("Cod", codigo);
            cst.setString("Nombre", nombre);
            cst.setString("Descrip", descrip);
            cst.setDouble("Precio", precio);
            cst.setInt("Stock", stock);
            cst.setString("Categ", cate);
                        
            int rpta = cst.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this,"* "+ codigo+ " modificado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }


}
