
package GUI;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 *
 * @author jennifer
 */
public class Boleta extends javax.swing.JFrame {

    int i=1;
    
    public Boleta() {
        initComponents();   
        txtNumVen.setText("   "+Integer.toString(i));
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtPagar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtSub = new javax.swing.JTextField();
        txtIGV = new javax.swing.JTextField();
        txtTotal = new javax.swing.JTextField();
        btnCodigo = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtNumVen = new javax.swing.JTextField();
        txtCod = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNom = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCate = new javax.swing.JTextField();
        fondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 123, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 51));
        jLabel1.setText("BOLETA  \" FLORERIA \" ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 60, 164, 17);

        jLabel3.setText("CANTIDAD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 160, 60, 14);

        jLabel4.setText("Numero de Venta N.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(340, 20, 110, 40);

        jLabel5.setText("PAGAR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(400, 160, 50, 14);
        getContentPane().add(txtCant);
        txtCant.setBounds(180, 180, 90, 30);

        txtPrecio.setEditable(false);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(280, 180, 90, 30);

        txtPagar.setEditable(false);
        getContentPane().add(txtPagar);
        txtPagar.setBounds(380, 180, 90, 30);

        jLabel6.setText("SUBTOTAL");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 250, 70, 14);

        jLabel7.setText("TOTAL");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 330, 50, 20);

        jLabel8.setText("IGV");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(150, 280, 40, 20);

        txtSub.setEditable(false);
        getContentPane().add(txtSub);
        txtSub.setBounds(230, 240, 110, 30);

        txtIGV.setEditable(false);
        getContentPane().add(txtIGV);
        txtIGV.setBounds(230, 280, 110, 30);
        getContentPane().add(txtTotal);
        txtTotal.setBounds(230, 320, 110, 30);

        btnCodigo.setText("BUSCAR CODIGO");
        btnCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCodigoActionPerformed(evt);
            }
        });
        getContentPane().add(btnCodigo);
        btnCodigo.setBounds(400, 250, 135, 40);

        btnImprimir.setText("IMPRIMIR BOLETA");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });
        getContentPane().add(btnImprimir);
        btnImprimir.setBounds(400, 320, 135, 40);

        jLabel10.setText("PRECIO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 160, 50, 14);

        txtNumVen.setEditable(false);
        txtNumVen.setBorder(null);
        getContentPane().add(txtNumVen);
        txtNumVen.setBounds(450, 24, 40, 30);
        getContentPane().add(txtCod);
        txtCod.setBounds(180, 120, 90, 30);

        jLabel9.setText("CODIGO");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 100, 70, 14);

        jLabel11.setText("NOMBRE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(290, 100, 60, 14);

        txtNom.setEditable(false);
        getContentPane().add(txtNom);
        txtNom.setBounds(280, 120, 160, 30);

        jLabel12.setText("CATEGORIA");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(450, 100, 70, 14);

        txtCate.setEditable(false);
        getContentPane().add(txtCate);
        txtCate.setBounds(450, 120, 90, 30);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fondo.png"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(-80, 0, 700, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        double pro1,pro2,vup1,vup2,vtp1,vtp2,Subtotal=20,IGV,TOTAL;
        pro1=Double.parseDouble(txtCant.getText());
        vup1=Double.parseDouble(txtPrecio.getText());
        vtp1=pro1*vup1;
        String valt1=vtp1+"";
        txtPagar.setText(valt1);
        Subtotal=vtp1;
        String st=Subtotal+"";
        txtSub.setText(st);
        IGV=Subtotal*0.12;
        String ig=IGV+"";
        txtIGV.setText(ig);
        TOTAL=Subtotal+IGV;
        String t=TOTAL+"";
        txtTotal.setText(t);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCodigoActionPerformed
        // TODO add your handling code here: 
        String codigo = this.txtCod.getText();
        Connection con=null;
        Statement stm;
        ResultSet rs;
                
        try{
            stm = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"
            + "database=Floreria;user=sa;password=123456;").createStatement();
            String query = "Select * from Arreglo A, categoriaArreglo C where "+" A.cod ='"+ codigo + "' and A.Categ = C.Cod_cat";
            rs = stm.executeQuery(query);
            while (rs.next()){
                txtPrecio.setText(Double.toString(rs.getDouble("precio")));
                txtNom.setText(rs.getString("nombre"));
                txtCate.setText(rs.getString("nombre_cat"));  
                
            }
        }catch(SQLException ex){
            System.out.println(ex);
        }
        i = i + 1;
        
        
    }//GEN-LAST:event_btnCodigoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCodigo;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCate;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextField txtIGV;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtNumVen;
    private javax.swing.JTextField txtPagar;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtSub;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
