use Floreria;

--INGRESAR CATEGORIAS
INSERT INTO categoriaArreglo
VALUES ('C001','AMOR', 18);
INSERT INTO categoriaArreglo
VALUES ('C002','CUMPLEAÑOS', 24);
INSERT INTO categoriaArreglo
VALUES ('C003','NACIMIENTO', 19);
INSERT INTO categoriaArreglo
VALUES ('C004','INAGURACION/ANIVERSARIO', 12);
INSERT INTO categoriaArreglo
VALUES ('C005','NOVIAS', 20);
INSERT INTO categoriaArreglo
VALUES ('C006','ARREGLOS PRIMAVERALES', 33);
INSERT INTO categoriaArreglo
VALUES ('C007','PLANTAS', 13);
INSERT INTO categoriaArreglo
VALUES ('C008','DEFUNCIÓN', 20);


--INGRESAR ARREGLOS
--AMOR
INSERT INTO Arreglo
VALUES ('AMOR01','12 ROSAS Y FLORES', 'LATA ROJA CON ADORNO CORAZON DE 12 ROSAS ROJAS, HORTENSIAS, IRIS, ASTROMELIAS, LILIUM',189 ,20, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR02','60 ROSAS ROJAS', 'CAJA MASSIMA CON 60 ROSAS ROJAS',289 ,15, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR03','8 ROSAS ROJAS Y ASTROMELIAS', 'BASE DE CERÁMICA BLANCA CON DETALLE DECORADO CON 8 ROSAS ROJAS Y ASTROMELIAS',230 ,82, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR04','10 ROSAS ROJAS Y PACK AMOR', 'CAJA CON 10 ROSAS, OSITO ESTAMPADO, TAZA DE CERÁMICA Y VALES DE AMOR',160 ,15, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR05','CORAZÓN CON 27 ROSAS ROJAS', 'BASE CANASTA CORAZON CON 27 ROSAS ROJAS Y FOLLAJE',189 ,15, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR06','6 ROSAS ROJAS EN CAJA MASSIMA', 'CAJA MASSIMA CON 6 ROSAS ROJAS Y HELECHO ACOMPAÑADAS CON TRUFAS FRANCESAS MATHEZ ',140 ,15, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR07','18 ROSAS ROJAS', 'BASE CANASCA CORAZÓN CON 18 ROSAS ROJAS Y FOLLAJE',135 ,15, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR08','REGALO AMOR', 'CAJA DE REGALO CON 3 ROSAS ROJAS, LIBRO TE AMO, CHOCOLATES FERRERO ROCHER CORAZON Y GLOBO',160 ,20, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR09','10 TULIPANES', 'CANASTA CON 10 TULIPANES, FOLLAJE Y DETALLE DE ADORNO CORAZÓN',199 ,15, 'C001');
INSERT INTO Arreglo
VALUES ('AMOR10','7 ROSAS Y FLORES', 'BASE DE VIDRIO CON LAZO ROJO CON 7 ROSAS, ASTROMELIAS Y ADORNO CORAZÓN',129 ,25, 'C001');

--CUMPLEAÑOS
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS01','12 TULIPANES','CANASTA CON LAZO Y 12 TULIPANES DE COLORES VARIADOS',175 ,12 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS02','9 ROSAS','RAMO CON 9 ROSAS EN YUTE ROSADO DECOADO CON SOGUILLA',116 ,34 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS03','8 TULIPANES','BALDE HOJALATA DECORADO CON FIELTRO CORAZON CON 8 TULIPANES COLORES VARIADOS Y HORTENSIAS',159 ,20 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS04','HORTENSIAS Y GERBERAS','BASE DE VIDRIO CON HORTENSIAS, GERBERAS DE COLRES Y ADORNADO CON PAJARITO ROSADO',99 ,23 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS05','CAJA MASSIMA Y ASTI MARTINI','CAJA MASSIMA CON ASTROMELIAS, HORTENSIAS Y ASTI MARTINI 200ML',140 ,12 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS06','ROSAS Y CHANDON ROSÉ','CANASTA CON 4 ROSAS ROJAS, FLORES Y CHANDON ROSÉ 750ML',180 ,20 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS07','ROSE CREMAS Y OSO BRINDLE','BASE DE MADERA VINTAGE CON 5 ROSAS CREMAS, FOLLAJE Y LINDO OSO BRINDLE',125 ,23 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS08','SENTIRME VIVO','LINDA TORTA FLORAL CON MARGARITAS NIEVE, CLAVELES Y FLORES VARIADAS',110 ,34 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS09','HAPPY BIRTHDAY','ARREGLO CON ROSAS AMARILLAS, LIRIOS ANARANJADOS Y FLORES EN BASE DE CERÁMICA BLANCA',125 ,34 ,'C002');
INSERT INTO Arreglo
VALUES ('CUMPLEAÑOS10','FELIZ CUMPLEAÑOS','TIERNO CACHORRITO FLORAL Y FLORES DE ESTACIÓN EN LINDA CANASTA DE MIMBRE',110 ,25 ,'C002');

--NACIMIENTO
INSERT INTO Arreglo
VALUES ('NACIMIENTO01','ROSAS Y FLOR DE PELUCHE','BASE DE CERÁMICA ROSADA CON 5 ROSAS, FLORES Y FLOR DE PELUCHE BABY BOY',149,23,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO02','ROSAS Y ZAPATITOS DE CURERO','CANASCA DE 5 ROSAS, FLORES Y ZAPATITOS DE CUERO',189,18,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO03','FLORES Y ZAPATITOS NIÑA','CANASTA ROSADA CON LILIUM Y FLORES VARIADAS Y PAR DE ZAPATITOS DE CUERO',199,19,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO04','FLORES Y GLOBO','BASE A CUADROS CON MARIPOSAS, CON FLORES VARIADAS, ESTACA CIGüEÑA NACIMIENTO Y GLOBO',149,45,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO05','TULIPAN ROSADO Y GLOBO','CAJA BLANCA CON UN TULIPAN ROSADO, OSITO CELESTE Y LAZO ROSADO Y GLOBO',62,50,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO06','FLORES Y MY FIRST HUGUETTE','BASE METALICA CON LILIUM, GIRASOLES, FLORES ACOMPAÑADA CON MY FIRST HUGUETTE ROSADA',149,35,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO07','SUSURROS DE AMOR','ARREGLA CON 10 ROSAS ROSADAS, 4 GERBERAS Y FLORES VARIADAS',169,25,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO08','CB02','ARREGLO BEBE CON ROSAS AMARILLAS, LILIUM BLANCO, FINO FOLLAJE',186,56,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO09','COCHECITO DE FELIZIDAD','ARREGLO CON LILIUM, 10 ROSAS AMARILLAS, 13 AMRGARITAS, CLAVELES, ASTROMELIAS Y COPROSMA',175,37,'C003');
INSERT INTO Arreglo
VALUES ('NACIMIENTO10','CUNA DE AMOR CON KIT BUHO','ARREGLO CON 3 LILIUMS, 3 IRIS, 5 ROSAS LILA, 9 MARGARITAS, CLAVELES, COPROSMA, GARDENIAS Y WAX',249,45,'C003');

--INAUGURACION
INSERT INTO Arreglo
VALUES ('INAUGURACION01','ROSAS GERBERAS EN TRIPODE','ARREGLO EN TRIPODE METAL CON 24 ROSAS , 8 GERBERAS,Y ASTROMELIAS',310,15,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION02','ROSAS EN TRIPODE','ARREGLO EN TRIPODE DE METAL CON ROSAS Y LILIUM',460,20,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION03','GERBERAS Y ROSAS','TRÍPODE DE METAL CON ROSAS IMPORTADAS, VARAS LILIUM Y FOLLAJE',275,35,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION04','TULIPANES, ROSAS Y FLORES','CAJA DE MAREDA VINTAGE CON TULIPANE, ROSAS, GERBERAS, ORTENSIAS, ASTROMELIAS, FOLLAJES',180,23,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION05','8 ROSAS Y ASTROMELIAS','FLORERO DE CERÁMICA CON 8 ROSAS Y ASTROMELIAS',180,56,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION06','SOFIA ','ARREGLO FLORAL CON 10 TULIPANES, DOCENA DE ROSAS, CLAVELES Y DOGOS EN CAJA DE CERÁMICA',245,10,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION07','TENTACION','CANASTA CON 2 DOCENAS DE ROSAS',230,34,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION08','SUMAQ','ARREGLO CON 20 TULIPANES EN BALDE DE HOJALATA',240,12,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION09','NOEMI','CANASTA DE MIMBRE CON 10 TULIPANES, MEDIA DOCENA DE ROSAS',180,34,'C004');
INSERT INTO Arreglo
VALUES ('INAUGURACION10','24ROSAS','FLORERO DE CERÁMICA CON 24 ROSAS Y FOLLAJE',180,12,'C004');


--NOVIAS
INSERT INTO Arreglo
VALUES ('NOVIAS01','BOU01','BOUQUET DE 24 ROSAS Y FOLLAJE',165,26,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS02','BOU02','BOUQUET DE 24 ROSAS, LILIOPES Y FOLLAJE',200,24,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS03','BOU03','BOUQUET DE 24 ROSAS , CARTUCHOS MORADOS Y FOLLAJE',220,35,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS04','BOU04','BOUQUET DE 24 ROSAS Y FOLLAJE',200,55,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS05','BOU05','BOUQUET DE 18 ROSAS Y FOLLAJE',200,22,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS06','BOU06','BOUQUET DE 12 ROSAS,HORTENSIAS,FRESIAS Y FOLLAJE',165,59,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS07','BOU07','BOUQUET DE 12 ROSAS , CARTUCHOS,GERBERAS Y FOLLAJE',175,30,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS08','BOU08','BOUQUET DE 18 ROSAS,LILIOPES Y FOLLAJE',200,9,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS09','DAM01','CANASTA DE MIMBRE PARA DAMITA DECORADA CON PINO,PETALOS DE ROSA Y FOLLAJE',65,40,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS10','DAM02','CANASTA DE MIMBRE PARA DAMITA DECORADA CON MIRTO,PETALOS DE ROSA Y FOLLAJE',55,60,'C005');
INSERT INTO Arreglo
VALUES ('NOVIAS11','DAM03','CORONA PARA DAMITA DE FLORES Y FOLLAJE',35,65,'C005');


--PRIMAVERALES
INSERT INTO Arreglo
VALUES ('PRIMAVERALES01','ROSAS Y TULIPANES','CANASTA CON 3 TULIPANES, 7 ROSAS ROJAS, FLORES VARIADAS Y DECORADO CON ADORNO PRIMAVERAL',199,21,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES02','FLORES Y GLOBO 9"','MACETA MARIPOSA CON FLORES PRIMAVERALES Y GLOBO 9"',129,33,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES03','FLORAL ROSAS','ARREGLOR FLORAL EN PORTALAPICERO CON PELUCHE Y UN GLOBO DE REGALO',72,40,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES04','FLORAL ROSAS Y CARTUCHOS','CARTUCHOS Y ROSAS ACOMPAÑADAS DE FINO FOLLAJE Y FLOR DE CEBOLLA',91,15,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES05','PRIM01','ARREGLO PRIMAVERAL EN CANASTA O BASE CERAMICA, CON FLORES DE ESTACION Y FOLLAJE',80,25,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES06','PRIM02','ARREGLO PRIMAVERAL BASE CERAMICA, CON FLORES DE ESTACION Y FOLLAJE',180,30,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES07','PRIM03','ARREGLO PRIMAVERAL EN CANASTA DE MIMBRE, CON FLORES DE ESTACION Y FOLLAJE',150,45,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES08','CAJA DE FLORES','ELEGANTE ARREGLO FLORAL DE ROSAS, CLAVELES Y LILIUM CON FINO FOLLAJE EN CAJA VINTAGE',185,20,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES09','ARREGLO PRIMAVERAL CON IRIS','ARREGLO CON 6 GIRASOLES,LILIUM MELON,IRIS,HORTENSIAS,ACHILIAS Y FOLLAJE',109,15,'C006');
INSERT INTO Arreglo
VALUES ('PRIMAVERALES10','ARREGLO 7 ROSAS','ARREGLO CON 7 ROSAS MELON Y ROJAS,3 LILIUM STARGAZER,2 GERBERAS BLANCAS Y FOLLAJE',99,10,'C006');


--PLANTAS
INSERT INTO Arreglo
VALUES ('PLANTAS01','LUCKY BAMBU TORRE','PLANTA DE LUCKY BAMBU EN FORMA DE TORRE CON BASE REDONDA DE CERAMICA',160,35,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS02','AGLONEMA','PLANTA DE AGLONEMA VARIEGADA EN UNA MACETA DE CERAMICA',90,45,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS03','ARBOL CHICO DE LA VIDA','ARBOL CON PIEDRAS SEMIPRECIOSAS',55,25,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS04','CACTUS INJERTADO ROJO','DECORATIVO CACTUS INJERTADO EN MACETA DE CERAMICA',65,30,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS05','DOBLE VARA','MACETA DE CERAMICA NEGRA CON PLANTA DE PHALAENOPSIS DOBLE VARA',230,60,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS06','KOKEDAME MINI ANTHURIO ','PLANTA ANTHURIO DE KOKEDAME',110,25,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS07','MACETA CEMENTO MEDIA LUNA','MACETA DE CEMENTO MODELO MEDIA LUNA DE 8CM x 12CM CON CACTUS',55,50,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS08','MACETA CON ANTHURIO','PLANTA DE ANTHURIO MINIATURA DE FLORES ROJAS EN PORTAMACETA DE CERAMICA',110,16,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS09','PLANTA DE ORQUIDEA PHALAENOPSIS','PLANTA DE ORQUIDEA PHALAENOPSIS EN UNA MACETA DE VIDRIO',230,56,'C007');
INSERT INTO Arreglo
VALUES ('PLANTAS10','PLANTA CHEFLERA','PLANTA EN MACETA, MIDE 160CM',192,40,'C007');

--DEFUNCION
INSERT INTO Arreglo
VALUES ('DEFUNCION01','LAGRIMA DE PISO','LAGRIMA DE PISO CON ROSAS BLANCAS,GLADIOLOS,CLAVELES,PALMERAS Y FLORES',230,25,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION02','LAGRIMA GRANDE CON TRIPODE','LAGRIMA EN TRIPODE CON ROSAS,POMPO,PALMERAS Y FLORES',340,20,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION03','CORONA GRANDE1','CORONA EN TRIPODE CON ROSAS,LILIUM,ASTROMELIAS Y FLORES',360,40,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION04','CORONA GRANDE2','CORONA EN TRIPODE CON ROSAS,ALELIES,CLAVELES Y FLORES',360,30,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION05','CORONA GRANDE3','CORONA EN TRIPODE CON ROSAS,IRIS,PALMERAS Y FLORES',360,30,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION06','CORONA MEDIANA','CORONA EN TRIPODE CON ROSAS,GERBERAS,LILIUM Y FLORES',305,18,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION07','CORONA MEDIANA2','CORONA EN TRIPODE CON GERBERAS,ASTROMELIAS,CLAVELES Y FLORES',260,12,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION08','CORONA CON CLAVELES','CORONA CON 120 CLAVELES ROJOS Y FOLLAJES',370,5,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION09','CRUZ CON POMPOS','CRUZ GRANDE CON POMPOS, 18 ROSAS, FLORES Y FOLLAJE',350,45,'C008');
INSERT INTO Arreglo
VALUES ('DEFUNCION10','CRUZ CON ROSAS','CRUZ CON 12 ROSAS CREMAS , CLAVELES Y FLORES',300,10,'C008');