/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JOptionPane;
import Conexion.Conexion;
import UpperEssential.UpperEssentialLookAndFeel;
import java.sql.*;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
/**
 *
 * @author Admin
 */
public class EliminarArreglo extends javax.swing.JFrame {

    CallableStatement cst;
    Connection cn;
    Statement stm;
    ResultSet rs;
    
    public EliminarArreglo() {
        initComponents();
        CargarCategoria();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar1 = new javax.swing.JButton();
        btnLista = new javax.swing.JButton();
        btnLista1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxCategoria = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1600, 915));
        setMinimumSize(new java.awt.Dimension(1600, 915));
        setPreferredSize(new java.awt.Dimension(1600, 915));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 24)); // NOI18N
        jLabel1.setText("BUSCAR CODIGO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 290, 430, 60);

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblLista);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 360, 430, 460);

        jLabel2.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel2.setText("INGRESAR CODIGO A ELIMINAR");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(530, 310, 410, 70);

        txtCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CODIGO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Semilight", 1, 24))); // NOI18N
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(580, 390, 290, 80);

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(590, 510, 260, 90);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1430, 790, 110, 60);

        btnIngresar.setBackground(new java.awt.Color(255, 255, 255));
        btnIngresar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnIngresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/8761.png"))); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIngresar);
        btnIngresar.setBounds(1160, 300, 310, 70);

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/edit2_icon-icons.com_61199.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(1160, 390, 310, 70);

        btnEliminar1.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnEliminar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        btnEliminar1.setText("Eliminar");
        btnEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar1);
        btnEliminar1.setBounds(1160, 480, 310, 70);

        btnLista.setBackground(new java.awt.Color(255, 255, 255));
        btnLista.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/list-on-a-notebook-stroke-symbol_icon-icons.com_57808.png"))); // NOI18N
        btnLista.setText("Lista     ");
        btnLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListaActionPerformed(evt);
            }
        });
        getContentPane().add(btnLista);
        btnLista.setBounds(1160, 570, 320, 70);

        btnLista1.setBackground(new java.awt.Color(255, 255, 255));
        btnLista1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        btnLista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Vendedor.png"))); // NOI18N
        btnLista1.setText("Trabajadores");
        btnLista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLista1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLista1);
        btnLista1.setBounds(1160, 660, 320, 70);

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel4.setText("Bienvenido");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(1190, 220, 280, 70);

        fondo1.setFont(new java.awt.Font("Segoe UI Semilight", 1, 36)); // NOI18N
        fondo1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(fondo1);
        fondo1.setBounds(1130, 210, 380, 560);

        jLabel3.setFont(new java.awt.Font("Segoe Script", 3, 160)); // NOI18N
        jLabel3.setText("Rosa Belén");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 10, 960, 180);

        cbxCategoria.setFont(new java.awt.Font("Segoe UI Semilight", 1, 18)); // NOI18N
        cbxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCategoriaActionPerformed(evt);
            }
        });
        getContentPane().add(cbxCategoria);
        cbxCategoria.setBounds(190, 210, 320, 50);

        jLabel11.setFont(new java.awt.Font("Segoe UI Semilight", 1, 24)); // NOI18N
        jLabel11.setText("CATEGORIA:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 220, 220, 32);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String codigo;
        
        codigo = this.txtCodigo.getText();
        eliminarArreglo(codigo);
        
        EntradaAdmin entrar = new EntradaAdmin();
        entrar.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        close();
        //        JOptionPane.showMessageDialog(null, "Hasta Luego");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
        RegistrarArreglo entrar = new RegistrarArreglo();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        ModificarArreglo entrar = new ModificarArreglo();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar1ActionPerformed
        // TODO add your handling code here:
        EliminarArreglo entrar = new EliminarArreglo();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnEliminar1ActionPerformed

    private void btnListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListaActionPerformed
        // TODO add your handling code here:
        EntradaAdmin entrar = new EntradaAdmin();
        entrar.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListaActionPerformed

    private void btnLista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLista1ActionPerformed

    private void cbxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCategoriaActionPerformed
        listarCategoria();
        Llenar();
    }//GEN-LAST:event_cbxCategoriaActionPerformed
     public void CargarCategoria(){
        Connection cn=null;
        Vector registros=null;
         try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            cn=DriverManager.getConnection("jdbc:sqlserver://localhost;databaseName=Floreria;"
               +"user=sa;password=123456");
            Statement stm=cn.createStatement();
            String query2="Select distinct * from categoriaArreglo";
            ResultSet rs=stm.executeQuery(query2);
            registros=new Vector();
            while(rs.next()){
                cbxCategoria.addItem(rs.getString("nombre_cat"));                
            }
        }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane, e.getMessage());    
        }catch(ClassNotFoundException e){}

    }
    
    private Vector listarCategoria() {
         Connection con=null;
         Statement stm=null;
         Vector reg=null;
         try{
         con = Conexion.getConexion();
         stm=con.createStatement();
         ResultSet rs = stm.executeQuery("SELECT * FROM Arreglo A JOIN categoriaArreglo C"
                 + " ON A.categ = C.cod_cat ");
         reg = new Vector();

             while(rs.next()){
             Vector item = new Vector();
             item.add(rs.getString("cod"));
             item.add(rs.getString("nombre"));
             //item.add(rs.getInt("stock"));
             //item.add(rs.getString("nombre_cat"));
             reg.add(item);
             }
         }
         catch(Exception e){
         System.out.print(e);
         }
         return reg;
    }
        private Vector listar() {
         Connection con=null;
         Statement stm=null;
         Vector reg=null;
         try{
         con = Conexion.getConexion();
         stm=con.createStatement();
         ResultSet rs = stm.executeQuery("SELECT * FROM Arreglo A JOIN categoriaArreglo C"
                 + " ON A.categ = C.cod_cat and nombre_cat='"+cbxCategoria.getSelectedItem()+"' ");
         reg = new Vector();

             while(rs.next()){
             Vector item = new Vector();
             item.add(rs.getString("cod"));
             item.add(rs.getString("nombre"));
             reg.add(item);
             }
         }
         catch(Exception e){
         System.out.print(e);
         }
         return reg;
    }
//    private Vector listar() {
//         Connection con=null;
//         Statement stm=null;
//         Vector reg=null;
//         try{
//         con = Conexion.getConexion();
//         stm=con.createStatement();
//         ResultSet rs = stm.executeQuery("SELECT * FROM Arreglo "
//                 + "ORDER BY COD;");
//         reg = new Vector();
//
//             while(rs.next()){
//             Vector item = new Vector();
//             item.add(rs.getString("cod"));
//             item.add(rs.getString("nombre"));
//             reg.add(item);
//             }
//         }
//         catch(Exception e){
//         System.out.print(e);
//         }
//         return reg;
//    }

    private void Llenar() {
        Vector colu = new Vector();
        colu.addElement("Codigo");
        colu.addElement("Nombre");       
        Vector reg = new Vector();
        reg = listar();
        DefaultTableModel dtm = new DefaultTableModel(reg, colu);
        this.tblLista.setModel(dtm);
        
    }
    
        private void close(){
        if (JOptionPane.showConfirmDialog(rootPane, "¿Desea Volver al Inicio?",
                "Cerrar Ventana", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
//          Marca_salida();
          Login c = new Login();
          c.setVisible(true);
          dispose();
        }          
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarArreglo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
 UIManager.setLookAndFeel(new UpperEssentialLookAndFeel());
        UIManager.setLookAndFeel(new UpperEssentialLookAndFeel("C:\\Users\\Janet\\Desktop\\26-11-17\\Lib UpperEssential\\Chocolate.theme"));
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarArreglo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminar1;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLista;
    private javax.swing.JButton btnLista1;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxCategoria;
    private javax.swing.JLabel fondo1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLista;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables

    private void eliminarArreglo(String codigo) {
        try {
            cst = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;"
            + "database=Floreria;user=sa;password=123456;").prepareCall("{call sp_Eliminar(?)}");            
            cst.setString("Cod", codigo);
                        
            int rpta = cst.executeUpdate();
            if (rpta == 1) {
                JOptionPane.showMessageDialog(this,"* "+ codigo+ " eliminado correctamente!!", "Atencion", JOptionPane.INFORMATION_MESSAGE);
            }            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

}
